<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="10" passed="8">
  <reporter-output>
    <line>
      <![CDATA[Priority one TC]]>
    </line>
    <line>
      <![CDATA[AlwaysRun]]>
    </line>
    <line>
      <![CDATA[TimeOut=1ms->it may or may not occur]]>
    </line>
    <line>
      <![CDATA[Failing it as tutor mentioned]]>
    </line>
    <line>
      <![CDATA[enabled=true]]>
    </line>
    <line>
      <![CDATA[expectedException BEFORE ArithmeticException]]>
    </line>
    <line>
      <![CDATA[Invocating 2 times]]>
    </line>
    <line>
      <![CDATA[Invocating 2 times]]>
    </line>
    <line>
      <![CDATA[enabled=false]]>
    </line>
    <line>
      <![CDATA[Test Description]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="4823" started-at="2017-09-04T10:38:58Z" finished-at="2017-09-04T10:39:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4823" started-at="2017-09-04T10:38:58Z" finished-at="2017-09-04T10:39:03Z">
      <class name="org.PriorityTest">
        <test-method status="PASS" signature="ztest1()[pri:-1, instance:org.PriorityTest@5056dfcb]" name="ztest1" duration-ms="38" started-at="2017-09-04T16:08:59Z" finished-at="2017-09-04T16:08:59Z">
          <reporter-output>
            <line>
              <![CDATA[Priority one TC]]>
            </line>
          </reporter-output>
        </test-method> <!-- ztest1 -->
        <test-method status="PASS" signature="atest3()[pri:0, instance:org.PriorityTest@5056dfcb]" name="atest3" duration-ms="5" started-at="2017-09-04T16:08:59Z" finished-at="2017-09-04T16:08:59Z">
          <reporter-output>
            <line>
              <![CDATA[AlwaysRun]]>
            </line>
          </reporter-output>
        </test-method> <!-- atest3 -->
        <test-method status="FAIL" signature="btest6()[pri:0, instance:org.PriorityTest@5056dfcb]" name="btest6" duration-ms="2039" started-at="2017-09-04T16:08:59Z" finished-at="2017-09-04T16:09:01Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:289)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:246)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:667)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
            <line>
              <![CDATA[TimeOut=1ms->it may or may not occur]]>
            </line>
          </reporter-output>
        </test-method> <!-- btest6 -->
        <test-method status="FAIL" signature="ktest8()[pri:0, instance:org.PriorityTest@5056dfcb]" name="ktest8" duration-ms="2007" started-at="2017-09-04T16:09:01Z" finished-at="2017-09-04T16:09:03Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:289)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:246)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:667)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
            <line>
              <![CDATA[Failing it as tutor mentioned]]>
            </line>
          </reporter-output>
        </test-method> <!-- ktest8 -->
        <test-method status="PASS" signature="mtest4()[pri:0, instance:org.PriorityTest@5056dfcb]" name="mtest4" duration-ms="8" started-at="2017-09-04T16:09:03Z" finished-at="2017-09-04T16:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[enabled=true]]>
            </line>
          </reporter-output>
        </test-method> <!-- mtest4 -->
        <test-method status="PASS" signature="ntest7()[pri:0, instance:org.PriorityTest@5056dfcb]" name="ntest7" duration-ms="33" started-at="2017-09-04T16:09:03Z" finished-at="2017-09-04T16:09:03Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at org.PriorityTest.ntest7(PriorityTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[expectedException BEFORE ArithmeticException]]>
            </line>
          </reporter-output>
        </test-method> <!-- ntest7 -->
        <test-method status="PASS" signature="ttest5()[pri:0, instance:org.PriorityTest@5056dfcb]" name="ttest5" duration-ms="25" started-at="2017-09-04T16:09:03Z" finished-at="2017-09-04T16:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[Invocating 2 times]]>
            </line>
          </reporter-output>
        </test-method> <!-- ttest5 -->
        <test-method status="PASS" signature="ttest5()[pri:0, instance:org.PriorityTest@5056dfcb]" name="ttest5" duration-ms="16" started-at="2017-09-04T16:09:03Z" finished-at="2017-09-04T16:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[Invocating 2 times]]>
            </line>
          </reporter-output>
        </test-method> <!-- ttest5 -->
        <test-method status="PASS" signature="wtest41()[pri:0, instance:org.PriorityTest@5056dfcb]" name="wtest41" duration-ms="10" started-at="2017-09-04T16:09:03Z" finished-at="2017-09-04T16:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[enabled=false]]>
            </line>
          </reporter-output>
        </test-method> <!-- wtest41 -->
        <test-method status="PASS" signature="ztest2()[pri:0, instance:org.PriorityTest@5056dfcb]" name="ztest2" duration-ms="14" started-at="2017-09-04T16:09:03Z" description="kd;lfkd;s" finished-at="2017-09-04T16:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[Test Description]]>
            </line>
          </reporter-output>
        </test-method> <!-- ztest2 -->
      </class> <!-- org.PriorityTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
